Merge from log events
multiversx/mx-chain-core-go pull request #241
Opened 2023-07-05 13:42 UTC by matei-p

2023-07-11 10:42 UTC, iulianpascalau requested changes
please merge the original feat/ branch

2023-07-11 13:55 UTC, iulianpascalau submitted a review, later dismissed

2023-07-11 13:55 UTC, sasurobert submitted a review, later dismissed

2023-07-12 07:52 UTC, sasurobert approved these changes

2023-07-12 07:53 UTC, merged