add on-the-fly mutexes by key
multiversx/mx-chain-core-go pull request #322
Opened 2024-09-18 11:30 UTC by AdoAdoAdo

2024-09-20 12:02 UTC, raduchis requested changes

2024-09-20 12:43 UTC, AdoAdoAdo commented on core/sync/keymutex.go
> +	km.getForRUnlock(key).rUnlock()
created on getForRUnlock if not existing, so that it panics because of an RUnlock on an unlocked mutex instead of dereferencing a nil pointer.

2024-09-20 12:43 UTC, AdoAdoAdo commented on core/sync/keymutex.go
> +	km.getForUnlock(key).unlock()
created on getForUnlock if not existing, so that it panics because of an Unlock on an unlocked mutex instead of dereferencing a nil pointer.

2024-09-25 11:17 UTC, cristure approved these changes

2024-09-25 11:18 UTC, merged