Consensus separation - common components
multiversx/mx-chain-core-go pull request #85
Opened 2022-08-11 12:29 UTC by ssd04

2022-08-12 09:09 UTC, AdoAdoAdo requested changes
please re-target the branch to a feat branch

2022-08-30 06:59 UTC, iulianpascalau commented on core/interface.go
> +// InterceptedDebugger defines an interface for debugging the intercepted data
mixed feelings about declaring this interface here. Also, for the Iterceptor and EpochStartActionHandler as they do not quite define the core business logic of elrond-go.

2022-09-01 10:27 UTC, AdoAdoAdo approved these changes

2022-09-22 08:02 UTC, iulianpascalau commented on core/interface.go
> +// InterceptedDebugger defines an interface for debugging the intercepted data
will remain as it is, for now

2022-09-22 08:02 UTC, iulianpascalau approved these changes

2025-11-10 15:48 UTC, closed without merging